### ISSUE TITLE
Starting from zero

### ISSUE THREAD

**Issue by GiantAmethyst** [GiantAmethyst/SkyBlock#10]
I'm going to fully recode the project as It has a really messy source.
Also, the next version will be 2.0 instead 0.2.0.

If you've got any sort of suggestion, my ears are open, just comment below.

**Comment by Skull3x** [comment]
@GiantQuartz We could add some mobs and NPC's that you can store items in 😄

**Comment by Skull3x** [comment]
@GiantQuartz That as well as more powerful types of mobs, similar to bosses but not too powerful. I have successfully created that and it's quite amazing. With that we could use the other spawn eggs that have no function like 383:1 -  4, I believe there are more non used spawn eggs but 4 is where I stopped looking. 😃

**Comment by XShockinFireX** [comment]
@Skull3x Yep, i also found that spawn eggs with id's of 383:4 - 9 are usable, and many more after 383:28; This will be helpful with the mobs. :smile:

**Comment by GiantQuartz** [comment]
@Skull3x @XShockinFireX The item isn't a problem, we can just create a custom item or set it a custom name to use it as we want. Anyway, these features are not going to be included on SkyBlock. The v2.0 is going to include a flexible API to let developers do their own extensions.

**Comment by JackSlacks** [comment]
Looks very promising. I'd recommend changing the "/sb <>" command prefix to /"is <>", since I think most players are used to this from the pc version. Combine "/sb join" and "/sb home" into one command, and automatically teleport the player to the island after creation.  Possibly make a language file and make the chest inventory customizable.

**Comment by GiantQuartz** [comment]
:)
